### ISSUE TITLE
Ruleset format considerations

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/omnilinter#5]
For MVP phase, the main goal is extensibility, so it should be YAML + serde. It would allow fast start with e.g. the following format:
```yaml
- title: fix trailing whitespace
  files: *.*
  match: " $"
```

and then allow extending it with new conditions, rule and condition properties. It would eventually evolve into something more ugly like
```yaml
rules:
- title: fix trailing whitespace
  tags: [foo, bar]
  conditions:
  - !files
    glob: "*.*"
    first_only: true
  - !files
    glob: "*.*"
    first_only: true
  - !match
    pattern: " $"
    ignore_case: true
```
yet still be extensible. With custom (de)serializers, it could be beautified somewhat
```yaml
rules:
- title: fix trailing whitespace
  tags: [foo, bar]
  conditions:
  - files: **.*"
    first_only: true
  - files "*.*"
    first_only: true
  - match: " $"
    ignore_case: true
```
but not sure if it's worth the complication.

As the final solution, it would be feasible to switch to a custom format, because of the following reasons:
- Shorter and flattier structure, as the format would not require nested container for conditions which can have multiple instances of the same key.
  ```yaml
    conditions:
    - files: "*.foo"
    - files: "*.bar"
  ```
  becomes
  ```
  files "*.foo"
  files "*.bar"
  ```
- Cleaner syntax
  - No need for extra indentation
  - No need for key/value separators
- Allows custom constructions, such as visually distinctive pattern for rule name/title
    ```
    [fix trailing whitespace]
    files "*.*"
    match " $"
    ```
- Allows custom handling of whitespace, quotes, and escaping, which would could make certain tokens more readable due to reduced number of backslashes, e.g. `match /['"]/` instead of `match '[\'"]'` and `files *.c *.cpp` instead of `files "*.c" "*.cpp"`.
- No need for extra syntactic constructs, e.g. `tags a b c` instead of `tags: [a, b, c]` or `tags: "a b c"` with additional split in the code.
- Better error reporting, being able to provide more context for parsing errors from custom parser.
